spring.application.name=havenly-stays
server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
#spring.datasource.password=hevenlypostgres

spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.apbkobhfnmcqqzqeeqss
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.data-source-properties.prepareThreshold=0
#spring.datasource.password=${DB_PASSWORD}
app.supabase.service-key=${SUPABASE_KEY}

# Add these two lines to ensure Hibernate doesn't get stuck during startup
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.packages-to-scan=com.asadi.havenly_stays.entity,com.hotelbooking.entity

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.jwt.secret=havenlySecretKeyForJwtTokenGeneration_change_this_in_prod
app.jwt.expiration-seconds=900
app.jwt.refresh-expiration-seconds=604800

app.supabase.url=https://xutmnrjeljnhvilfpsim.supabase.co
#app.supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dG1ucmplbGpuaHZpbGZwc2ltIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDA5MTgyNiwiZXhwIjoyMDg5NjY3ODI2fQ.vRuYbmmWL3v6QPwkKqAPBojtNcuMs3Kthp7aIGFvHqA
app.supabase.bucket=hotel-images


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.initialization-fail-timeout=0